<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8UdgM0r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8UdgM0r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8UdgM0r.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8UdgM0r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8UdgM0r\App_KernelDevDebugContainer([
    'container.build_hash' => '8UdgM0r',
    'container.build_id' => '726e03c9',
    'container.build_time' => 1640236744,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8UdgM0r');
