<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyyNfCX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyyNfCX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyyNfCX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyyNfCX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHyyNfCX\App_KernelDevDebugContainer([
    'container.build_hash' => 'HyyNfCX',
    'container.build_id' => '2a86740d',
    'container.build_time' => 1640236213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyyNfCX');
