<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8a7ZnlQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8a7ZnlQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8a7ZnlQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8a7ZnlQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8a7ZnlQ\App_KernelDevDebugContainer([
    'container.build_hash' => '8a7ZnlQ',
    'container.build_id' => '5247a48e',
    'container.build_time' => 1640235659,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8a7ZnlQ');
