<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/app']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/']], [], [], []],
    'new' => [[], ['_controller' => 'App\\Controller\\AppController::new'], [], [['text', '/new']], [], [], []],
    'ajaxupdate' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxupdate'], [], [['text', '/updatefav']], [], [], []],
    'update' => [['id'], ['_controller' => 'App\\Controller\\AppController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], [], []],
    'create' => [[], ['_controller' => 'App\\Controller\\AppController::create'], [], [['text', '/']], [], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\AppController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit']], [], [], []],
    'read' => [['id'], ['_controller' => 'App\\Controller\\AppController::read'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\AppController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
];
