version: '2'
services:
  nginx:
    image: nginx
    container_name: "symfony-nginx"
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony-app:/var/www/symfony-app
    depends_on:
      - phpfpm
      - database
  phpfpm:
    build: ./fpm
    container_name: "symfony-phpfpm"
    volumes:
      - ./symfony-app:/var/www/symfony-app
    depends_on:
      - database
  database:
    container_name: symfony-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql